### ISSUE TITLE
Error when destroying Firewall rules

### ISSUE THREAD

**Issue by Catskan** [cloudamqp/terraform-provider-cloudamqp#205] opened 2023-05-09 18:22 UTC
Hello everyone,

I manage my CloudAMQP instances by using Terraform and this official provider.
It working good, thanks to the team to do this work :).

I have an issue when I perform a destroy, only show in the first `terraform plan -destroy`
The output when apply this plan : 
`│ Error: DeleteNotification failed, status: 400, message: map[error_code:%!s(float64=40001) message:Your new firewall rules have not finished configuring yet,try again in a few minutes]`

I created those rules by using a loop

### main.tf:
```
locals {
  id           = values(data.aws_subnet.internet-facing).*.id
  cidr_block   = values(data.aws_subnet.internet-facing).*.cidr_block
  az           = values(data.aws_subnet.internet-facing).*.availability_zone
}

resource "cloudamqp_security_firewall" "firewall-settings" {
  instance_id = cloudamqp_instance.rmq-instance.id
  count       = length(local.id)
  dynamic "rules" {
    for_each = toset(local.cidr_block)
    content {
      ip          = rules.value
      description = local.az[count.index]
      ports       = []
      services    = ["AMQPS"]
    }
  }
  #This rule is to allow RabbitMQ management from Internet
  rules {
    ip       = "0.0.0.0/0"
    ports    = []
    services = ["HTTPS"]
  }
}
```

### Terraform commands:
1. `terraform plan -destroy -out plan.out`
2. `terraform apply plan.out`
```
        cloudamqp_security_firewall.firewall-settings[0]: Destroying... [id=231960]
        cloudamqp_security_firewall.firewall-settings[2]: Destroying... [id=231960]
        cloudamqp_security_firewall.firewall-settings[1]: Destroying... [id=231960]
        ncloudamqp_security_firewall.firewall-settings[1]: Still destroying... [id=231960, 10s elapsed]
        cloudamqp_security_firewall.firewall-settings[0]: Still destroying... [id=231960, 10s elapsed]
        cloudamqp_security_firewall.firewall-settings[1]: Still destroying... [id=231960, 20s elapsed]
        cloudamqp_security_firewall.firewall-settings[0]: Still destroying... [id=231960, 20s elapsed]
        cloudamqp_security_firewall.firewall-settings[0]: Still destroying... [id=231960, 30s elapsed]
        cloudamqp_security_firewall.firewall-settings[1]: Still destroying... [id=231960, 30s elapsed]
        cloudamqp_security_firewall.firewall-settings[0]: Destruction complete after 30s
        cloudamqp_security_firewall.firewall-settings[1]: Destruction complete after 30s
  │ Error: DeleteNotification failed, status: 400, message: map[error_code:%!s(float64=40001) 
    message:Your new firewall rules have not finished configuring yet,try again in a few minutes]
```
3. `terraform plan -destroy -out plan.out` (second time)
4. `terraform apply plan.out` (second time)
```
        cloudamqp_security_firewall.firewall-settings[2]: Destroying... [id=231960]
        cloudamqp_security_firewall.firewall-settings[2]: Destruction complete after 0s
        cloudamqp_instance.rmq-instance: Destroying... [id=231960]
```

Do you already know this bug ? And how to fix it ?

Thanks in advance

**Comment by dentarg** [comment] 2023-05-09 19:27
> Error: DeleteNotification failed, status: 400, message: map[error_code:%!s(float64=40001) message:Your new firewall rules have not finished configuring yet,try again in a few minutes]

I'll just comment on this so we are not confused in the future: it says `DeleteNotification` because there was a typo in go-api that I (just) fixed with https://github.com/84codes/go-api/commit/2306aecfda7c57004293d9dc6b8f1c715d2b30c2

**Comment by dentarg** [comment] 2023-05-09 19:28
@Catskan Are you destroying the resources very soon after you created them?

**Comment by dentarg** [comment] 2023-05-09 19:35
Okay, the issue is that, for Delete, we are not retrying 400 responses, which we do for Create and Update: https://github.com/84codes/go-api/blob/2306aecfda7c57004293d9dc6b8f1c715d2b30c2/api/security_firewall.go

Thanks for reporting this

**Comment by Catskan** [comment] 2023-05-09 20:33
> @Catskan Are you destroying the resources very soon after you created them?

Yes and not. This error is same for both. 
Just after creating and many minutes after the plan.

**Comment by tbroden84** [comment] 2023-05-12 07:11
@Catskan 
We have added retry functionality to the client library. This will retry deleting firewall settings. Just made a new release [v1.26.2](https://github.com/cloudamqp/terraform-provider-cloudamqp/releases/tag/v1.26.2). Will close this issue, please re-open this if you still encounter the issue.

**Closed by tbroden84** 2023-05-12 07:11 UTC
Labels: bug
